# Generated by Django 6.0.3 on 2026-04-07 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movies', models.ManyToManyField(blank=True, related_name='collections', to='movies.movie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('owner', 'title')},
            },
        ),
        migrations.CreateModel(
            name='WatchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_watch', 'Want to watch'), ('watching', 'Watching'), ('watched', 'Watched')], default='want_to_watch', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('watched_at', models.DateField(blank=True, null=True)),
                ('personal_note', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_entries', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-added_at',),
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
